
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: install mysql python libraries
  ansible.builtin.pip:
   executable: pip3.9
   name: "{{ item }}"
  loop:
  - cryptography
  - PyMySQL

- name: java and maven setup
  ansible.builtin.import_role:
    name: common
    tasks_from: java_setup.yaml

- name: import shipping data into mysql
  community.mysql.mysql_db:
    name: all
    state: import
    login_host: "{{ MYSQL_HOST }}"
    login_user: "{{ MYSQL_ROOT_USER }}"
    login_password: "{{ MYSQL_ROOT_PASSWORD }}"
    target: "{{ item }}"
  loop:
  -  /app/db/schema.sql
  - /app/db/app-user.sql 
  - /app/db/master-data.sql

- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml
