- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: 
  - maven
  - mysql 

- name: install dependences
  ansible.builtin.command: mvn clean package
  args:
   chdir: /app

- name: rename the the jar file
  ansible.builtin.command: mv target/shipping-{{ version }}.jar shipping.jar
  args:
   chdir: /app