- name: install python packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: 
     - python3 
     - gcc 
     - python3-devel

- name: install dependences 
  ansible.builtin.pip: 
    requirements: requirements.txt
    executable: pip3.9
  args:
      chdir: /app